Update verify.yml

diff --git a/.github/workflows/verify.yml b/.github/workflows/verify.yml
--- a/.github/workflows/verify.yml
+++ b/.github/workflows/verify.yml
@@ -22,4 +22,4 @@ jobs:
         run: ruby -v
 
       - name: List directory contents
-        run: ls -la /opt/hostedtoolcache/Ruby/3.2.6/x64/lib/ruby/gems/3.2.0/gems || echo "Directory not found"
+        run: ls -la /opt/hostedtoolcache/Ruby/3.2.4/x64/lib/ruby/gems/3.2.0/gems || echo "Directory not found"
